<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'KasApi\\' => array($vendorDir . '/kveldscholten/kasapi-php/src/KasApi'),
);
