<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit287e964948f86b5020c34620b89afe3c
{
    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'KasApi\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'KasApi\\' => 
        array (
            0 => __DIR__ . '/..' . '/kveldscholten/kasapi-php/src/KasApi',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit287e964948f86b5020c34620b89afe3c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit287e964948f86b5020c34620b89afe3c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit287e964948f86b5020c34620b89afe3c::$classMap;

        }, null, ClassLoader::class);
    }
}
